version: "3.8"

services:
  webapp:
    image: yourusername/webapp:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_DB: webapplication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: webapplication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
